### PR TITLE
New scaffold

### PR DESCRIPTION
**Pull request by PianoPenguin471**
Made scaffold swap to blocks slot and actually disabled sprint.

### CODE REVIEW

**Comment by Syz66** [comment]
Bro made a pr on his own repo 😹, anyways I'll check this out but I probably won't make any changes till tomorrow when I'm free.

**Comment by Cosmic-SC** [comment]
image
do this in pre (event.isPre() check) cuz it *might* flag for post

**Comment by Syz66** [comment]
> image
> do this in pre (event.isPre() check) cuz it _might_ flag for post

Thanks, I thought this was already added but I guess I was mistaken :(

**Comment by PianoPenguin471** [comment]
> image do this in pre (event.isPre() check) cuz it _might_ flag for post

Done

**Pull request merged**
