### PR TITLE
Add Third Person Rotations

### PR DESCRIPTION
**Pull request by Cosmic-SC**
yes.

### CODE REVIEW

**Comment by PianoPenguin471** [comment]
does this do the pitch too? Or is it just the Yaw?

**Comment by Zircta** [comment]
Piano, Just tested and it doesnt work at all, it just crashes

**Comment by PianoPenguin471** [comment]
> Piano, Just tested and it doesnt work at all, it just crashes

What is the crash log?

**Comment by Cosmic-SC** [comment]
> Piano, Just tested and it doesnt work at all, it just crashes

ahhhhh check logs i did the commit in github not intellij so idk if i forgor to write a semi colon or smth

**Comment by Cosmic-SC** [comment]
> does this do the pitch too? Or is it just the Yaw?

just yaw. If you want pitch you'll need a mixin for modelbiped and add some funny code to setRotationAngles function

**Pull request merged**
