### PR TITLE
Aura GCD Patch, Gui BugFixes/Tweaks & Fix RGBSlider Crash In BetaGUI - Completed

### PR DESCRIPTION
**Pull request by NerdHaxx**
Completed can be merged

### CODE REVIEW

**Comment by NerdHaxx** [comment]
i hope aura isnt broken

**Comment by Zircta** [comment]
What is GCD?

**Comment by NerdHaxx** [comment]
GCD = Greatest Common Divisor. it is used by many anticheats for detecting aura rotations

**Comment by NerdHaxx** [comment]
for example:

https://github.com/GladUrBad/Medusa/blob/master/Impl/src/main/java/com/gladurbad/medusa/check/impl/combat/aimassist/AimAssistE.java

**Pull request merged**
