### PR TITLE
Failed attempt at fixing KeepSprint

### PR DESCRIPTION
**Pull request by Zircta**
too lazy to explain it all, just look at the commit

### CODE REVIEW

**Comment by Cosmic-SC** [comment]
damn ill try to fix it i hope its not that hard

**Comment by Cosmic-SC** [comment]
nvm i thought u tried to make it with mixins only why did u create like 4 mixins just for an event? also that event is only used for keepsprint so its just bloat i recommend you hook keepsprint directly to keep sprint

**Comment by Zircta** [comment]
> nvm i thought u tried to make it with mixins only why did u create like 4 mixins just for an event? also that event is only used for keepsprint so its just bloat i recommend you hook keepsprint directly to mixins

Only 1 mixin is used for keepsprint, I deleted one (unused) and changed one (because it spammed logs), and the event is used for readiblity.

**Comment by Cosmic-SC** [comment]
> > nvm i thought u tried to make it with mixins only why did u create like 4 mixins just for an event? also that event is only used for keepsprint so its just bloat i recommend you hook keepsprint directly to mixins
> 
> Only 1 mixin is used for keepsprint, I deleted one (unused) and changed one (because it spammed logs), and the event is used for readiblity, but PianoPenguin already said he would work from where I left off anyways so it's alright.

alr cool :)

**Pull request closed without merging**
